package com.nowcoder.seckill.entity;

public class SRIRelation {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column share_records_img_relation.id
     *
     * @mbg.generated Tue Jun 29 10:57:53 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column share_records_img_relation.share_record_id
     *
     * @mbg.generated Tue Jun 29 10:57:53 CST 2021
     */
    private String shareRecordId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column share_records_img_relation.file_name
     *
     * @mbg.generated Tue Jun 29 10:57:53 CST 2021
     */
    private String fileName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column share_records_img_relation.id
     *
     * @return the value of share_records_img_relation.id
     *
     * @mbg.generated Tue Jun 29 10:57:53 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column share_records_img_relation.id
     *
     * @param id the value for share_records_img_relation.id
     *
     * @mbg.generated Tue Jun 29 10:57:53 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column share_records_img_relation.share_record_id
     *
     * @return the value of share_records_img_relation.share_record_id
     *
     * @mbg.generated Tue Jun 29 10:57:53 CST 2021
     */
    public String getShareRecordId() {
        return shareRecordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column share_records_img_relation.share_record_id
     *
     * @param shareRecordId the value for share_records_img_relation.share_record_id
     *
     * @mbg.generated Tue Jun 29 10:57:53 CST 2021
     */
    public void setShareRecordId(String shareRecordId) {
        this.shareRecordId = shareRecordId == null ? null : shareRecordId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column share_records_img_relation.file_name
     *
     * @return the value of share_records_img_relation.file_name
     *
     * @mbg.generated Tue Jun 29 10:57:53 CST 2021
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column share_records_img_relation.file_name
     *
     * @param fileName the value for share_records_img_relation.file_name
     *
     * @mbg.generated Tue Jun 29 10:57:53 CST 2021
     */
    public void setFileName(String fileName) {
        this.fileName = fileName == null ? null : fileName.trim();
    }
}