package com.nowcoder.seckill.dao;

import com.nowcoder.seckill.entity.ShareRecords;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface ShareRecordsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_records
     *
     * @mbg.generated Fri Jun 04 12:46:02 CST 2021
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_records
     *
     * @mbg.generated Fri Jun 04 12:46:02 CST 2021
     */
    int insert(ShareRecords record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_records
     *
     * @mbg.generated Fri Jun 04 12:46:02 CST 2021
     */
    ShareRecords selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_records
     *
     * @mbg.generated Fri Jun 04 12:46:02 CST 2021
     */
    List<ShareRecords> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_records
     *
     * @mbg.generated Fri Jun 04 12:46:02 CST 2021
     */
    int updateByPrimaryKey(ShareRecords record);
}