package com.nowcoder.seckill.dao;

import com.nowcoder.seckill.entity.SRIRelation;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface SRIRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_records_img_relation
     *
     * @mbg.generated Tue Jun 29 10:57:53 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_records_img_relation
     *
     * @mbg.generated Tue Jun 29 10:57:53 CST 2021
     */
    int insert(SRIRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_records_img_relation
     *
     * @mbg.generated Tue Jun 29 10:57:53 CST 2021
     */
    SRIRelation selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_records_img_relation
     *
     * @mbg.generated Tue Jun 29 10:57:53 CST 2021
     */
    List<SRIRelation> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_records_img_relation
     *
     * @mbg.generated Tue Jun 29 10:57:53 CST 2021
     */
    int updateByPrimaryKey(SRIRelation record);

    List<SRIRelation> selectByShareRecordId(String id);

    int deleteByShareRecordId(String id);
}