package com.nowcoder.seckill.dao;

import com.nowcoder.seckill.entity.User;
import com.nowcoder.seckill.entity.resultentity.UserResult;
import com.nowcoder.seckill.entity.resultentity.UserSimplifiedResult;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Tue Jan 19 14:37:36 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Tue Jan 19 14:37:36 CST 2021
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Tue Jan 19 14:37:36 CST 2021
     */
    User selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Tue Jan 19 14:37:36 CST 2021
     */
    List<User> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Tue Jan 19 14:37:36 CST 2021
     */
    int updateByPrimaryKey(User record);

    /**
     * 根据手机号查询用户
     *
     * @param phone
     * @return
     */
    User selectByPhone(String phone);

    UserResult selectByPrimaryKeySimplified(Integer id);

    List<UserResult> searchByPhoneSimplified(String phone);

    List<UserResult> searchByNicknameSimplified(String nickname);

    List<UserResult> searchByUsernameSimplified(String username);

    UserResult selectUserDetailByPrimaryKey(Integer id);
}